Name: Human-Custom
Species: 1
Parts:
- Name: SK_HUMN_BASE_01_01HEAD_HU01
  PartType: Head
  PartVersion: 1
- Name: SK_HUMN_BASE_02_04EBRR_HU01
  PartType: EyebrowRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_05EYEL_HU01
  PartType: EyeLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_05_07EARL_HU01
  PartType: EarLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_37TONG_HU01
  PartType: Tongue
  PartVersion: 1
- Name: SK_HUMN_BASE_02_03EBRL_HU01
  PartType: EyebrowLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_35NOSE_HU01
  PartType: Nose
  PartVersion: 1
- Name: SK_HUMN_BASE_05_08EARR_HU01
  PartType: EarRight
  PartVersion: 1
- Name: SK_HUMN_BASE_04_36TETH_HU01
  PartType: Teeth
  PartVersion: 1
- Name: SK_HUMN_BASE_01_06EYER_HU01
  PartType: EyeRight
  PartVersion: 1
- Name: SK_HUMN_BASE_02_02HAIR_HU01
  PartType: Hair
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_13ALWL_HU01
  PartType: ArmLowerLeft
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_14ALWR_HU01
  PartType: ArmLowerRight
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_15HNDL_HU01
  PartType: HandLeft
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_12AUPR_HU01
  PartType: ArmUpperRight
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_16HNDR_HU01
  PartType: HandRight
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_29ASHL_HU01
  PartType: AttachmentShoulderLeft
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_11AUPL_HU01
  PartType: ArmUpperLeft
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_10TORS_HU01
  PartType: Torso
  PartVersion: 1
- Name: SK_FANT_KNGT_17_17HIPS_HU01
  PartType: Hips
  PartVersion: 1
- Name: SK_FANT_KNGT_17_21FOTR_HU01
  PartType: FootRight
  PartVersion: 1
- Name: SK_FANT_KNGT_17_20FOTL_HU01
  PartType: FootLeft
  PartVersion: 1
- Name: SK_FANT_KNGT_17_19LEGR_HU01
  PartType: LegRight
  PartVersion: 1
- Name: SK_FANT_KNGT_17_18LEGL_HU01
  PartType: LegLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_09_09FCHR_HU01
  PartType: FacialHair
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_30ASHR_HU01
  PartType: AttachmentShoulderRight
  PartVersion: 1
ColorSet:
  Species: 1
  Name: Custom
  SourceColorPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_ColorMap.png
  SourceMetallicPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_MetallicMap.png
  SourceSmoothnessPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_SmoothnessMap.png
  SourceReflectionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_ReflectionMap.png
  SourceEmissionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_EmissionMap.png
  SourceOpacityPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_OpacityMap.png
ColorRows:
- ColorProperty: 1
  MainColor: 68493E
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 2
  MainColor: 674E45
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 3
  MainColor: 674E45
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 4
  MainColor: 3B3124
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 5
  MainColor: 3B3124
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 6
  MainColor: 68493E
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 7
  MainColor: 68493E
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 8
  MainColor: 68493E
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 9
  MainColor: 68493E
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 10
  MainColor: 68493E
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 11
  MainColor: 68493E
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 12
  MainColor: 68493E
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 13
  MainColor: 68493E
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 14
  MainColor: 68493E
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 15
  MainColor: E79A9C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 16
  MainColor: FFF3CE
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 17
  MainColor: E5D8AF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 18
  MainColor: E79A9C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 19
  MainColor: E79A9C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 20
  MainColor: D0D0D0
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 21
  MainColor: D0D0D0
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 22
  MainColor: 282119
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 23
  MainColor: 282119
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 24
  MainColor: 262626
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 25
  MainColor: 262626
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 26
  MainColor: 3B3125
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 27
  MainColor: 3B3125
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 28
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 29
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 30
  MainColor: 151515
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 31
  MainColor: 151515
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 32
  MainColor: 151515
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 33
  MainColor: 151515
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 34
  MainColor: CAA58E
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 35
  MainColor: 151515
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 36
  MainColor: 151515
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 37
  MainColor: CAA58E
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 38
  MainColor: 9A4C45
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 39
  MainColor: 6A3531
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 40
  MainColor: AFA382
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 41
  MainColor: 94896F
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 42
  MainColor: 3F556A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 43
  MainColor: 566470
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 44
  MainColor: 382F2A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 45
  MainColor: 3F4850
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 46
  MainColor: 363433
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 47
  MainColor: 3F556A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 48
  MainColor: 875829
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 49
  MainColor: 382F2A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 50
  MainColor: 3F4850
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 51
  MainColor: 363433
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 52
  MainColor: 3F556A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 53
  MainColor: 875829
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 54
  MainColor: 382F2A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 55
  MainColor: 3F4850
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 56
  MainColor: 363433
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 57
  MainColor: 6B513B
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 58
  MainColor: 483D34
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 59
  MainColor: 363433
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 60
  MainColor: 3F4850
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 61
  MainColor: 363433
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 62
  MainColor: 6B513B
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 63
  MainColor: 483D34
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 64
  MainColor: 363433
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 65
  MainColor: 3F4850
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 66
  MainColor: 363433
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 67
  MainColor: 875829
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 68
  MainColor: 3F556A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 69
  MainColor: 7F5A48
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 70
  MainColor: 907151
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 71
  MainColor: 483D34
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 72
  MainColor: 625343
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 73
  MainColor: 50443A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 74
  MainColor: 363433
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 75
  MainColor: 907151
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 76
  MainColor: 784D49
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 77
  MainColor: 625343
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 78
  MainColor: 50443A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 79
  MainColor: 363433
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 80
  MainColor: 907151
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 81
  MainColor: 784D49
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 82
  MainColor: 625343
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 83
  MainColor: 50443A
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 84
  MainColor: 363433
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 85
  MainColor: 907151
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 86
  MainColor: 784D49
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 87
  MainColor: 625343
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 88
  MainColor: 50443A
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 89
  MainColor: 363433
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 90
  MainColor: 907151
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 91
  MainColor: 784D49
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 92
  MainColor: 625343
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 93
  MainColor: 985D41
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 94
  MainColor: B5B6B5
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 95
  MainColor: 4C3A2D
  Metallic: B7B7B7
  Smoothness: B7B7B7
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 96
  MainColor: 282E3C
  Metallic: B7B7B7
  Smoothness: B7B7B7
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 97
  MainColor: 222221
  Metallic: B7B7B7
  Smoothness: B7B7B7
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 98
  MainColor: 72695E
  Metallic: B7B7B7
  Smoothness: B7B7B7
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 99
  MainColor: 2A2D31
  Metallic: B7B7B7
  Smoothness: B7B7B7
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 100
  MainColor: 4C3A2D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 101
  MainColor: 2D364C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 102
  MainColor: 2A2928
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 103
  MainColor: 8D806F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 104
  MainColor: 32363D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 105
  MainColor: 4C3A2D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 106
  MainColor: 2D364C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 107
  MainColor: 2A2928
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 108
  MainColor: 8D806F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 109
  MainColor: 32363D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 110
  MainColor: 3C574B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 111
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 112
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 113
  MainColor: 898580
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 114
  MainColor: 76726C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 115
  MainColor: 3C574B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 116
  MainColor: 504B45
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 117
  MainColor: 504B45
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 118
  MainColor: 7D7973
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 119
  MainColor: 6A6660
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 120
  MainColor: 3C574B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 121
  MainColor: 998B79
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 122
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 123
  MainColor: 898580
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 124
  MainColor: 76726C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 125
  MainColor: 3C574B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 126
  MainColor: 918473
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 127
  MainColor: 504B45
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 128
  MainColor: 7D7973
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 129
  MainColor: 6A6660
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 130
  MainColor: 3C574B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 131
  MainColor: 998B79
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 132
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 133
  MainColor: 898580
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 134
  MainColor: 76726C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 135
  MainColor: 3C574B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 136
  MainColor: 918473
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 137
  MainColor: 504B45
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 138
  MainColor: 7D7973
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 139
  MainColor: 6A6660
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 140
  MainColor: 3C574B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 141
  MainColor: 998B79
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 142
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 143
  MainColor: 898580
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 144
  MainColor: 76726C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 145
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 146
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 147
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 148
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 149
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 150
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 151
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 152
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 153
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 154
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 155
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 156
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 157
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 158
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 159
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 160
  MainColor: 9F8558
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 161
  MainColor: 654F2B
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 162
  MainColor: 161526
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 163
  MainColor: 474850
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 164
  MainColor: B09D6E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 165
  MainColor: B5904B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 166
  MainColor: 8D569F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 167
  MainColor: 723F83
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 168
  MainColor: 6CB0C1
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: 000000
- ColorProperty: 169
  MainColor: 619978
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: 000000
- ColorProperty: 170
  MainColor: 00FFE4
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 171
  MainColor: 0074FF
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 172
  MainColor: 9A9FA2
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 173
  MainColor: 949AA2
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 174
  MainColor: 8D997D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 175
  MainColor: 838865
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 176
  MainColor: 3B3936
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 177
  MainColor: 2E2C29
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 178
  MainColor: 8B8580
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 179
  MainColor: 5F6269
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 180
  MainColor: A0967F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 181
  MainColor: 897D63
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 182
  MainColor: 8B7B69
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 183
  MainColor: 746352
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 184
  MainColor: 785F49
  Metallic: AAAAAA
  Smoothness: AAAAAA
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 185
  MainColor: 695441
  Metallic: AAAAAA
  Smoothness: AAAAAA
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 186
  MainColor: 7A5F45
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 187
  MainColor: 614E3D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 188
  MainColor: 9C7B4F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 189
  MainColor: 746451
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 190
  MainColor: 63594B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 191
  MainColor: 7F715F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 192
  MainColor: BDB7B0
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 193
  MainColor: A8A39F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 194
  MainColor: 7D6652
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 195
  MainColor: 8E7661
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 196
  MainColor: 954039
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 197
  MainColor: 6D403D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 198
  MainColor: 7B7879
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 199
  MainColor: 565656
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
BlendShapes:
  BodyTypeValue: -100
  BodySizeValue: -100
  MuscleValue: 55.2000008
